version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    command: rabbitmq-server
    restart: on-failure

  tgbot:
    restart: on-failure
    build:
      context: ./src/tgbot/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./src/common:/code/common:ro
      - ./${USER_DATA}:${USER_DATA}
      - ./demo:/demo

  quality:
    restart: on-failure
    build:
      context: ./src/quality/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./src/common:/code/common:ro
      - ./src/models/quality:/code/models:ro
      - ./${USER_DATA}:${USER_DATA}
      - ./demo:/demo

  highlights:
    restart: on-failure
    build:
      context: ./src/highlights/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./src/common:/code/common:ro
      - ./src/models/highlights:/code/models:ro
      - ./${USER_DATA}:${USER_DATA}
      - ./demo:/demo

  music_recommendation:
    restart: on-failure
    build:
      context: ./src/music_recommendation/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./src/common:/code/common:ro
      - ./src/models/music:/code/models:ro
      - ./${USER_DATA}:${USER_DATA}
      - ./demo:/demo
      - ./genres:${MUSIC_DATA}

  video_audio_compose:
    restart: on-failure
    build:
      context: ./src/video_audio_compose/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./src/common:/code/common:ro
      - ./${USER_DATA}:${USER_DATA}
      - ./genres:${MUSIC_DATA}
      - ./demo:/demo
      - ./${VISBEAT_DATA}:${VISBEAT_DATA}
